[tool.poetry]
name = "youtube_base"
version = "0.1.0"
description = ""
authors = ["Kostiantyn"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
website = {path = "./website/"}
importlib = "^1.0.4"
django = "^5.0"
flake8 = "^6.1.0"
selenium = "^4.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
