[tool.poetry]
name = "root"
version = "0.1.0"
description = ""
authors = ["Kostiantyn"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
website = {path = "./website/"}
importlib = "^1.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
