name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - '*'

jobs:
  run_pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.7.0"]
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Poetry install
        run: poetry install
      - name: Start Django server
        run: |
          poetry run python youtube_base/manage.py runserver & sleep 10
      - name: Run migrations and fixtures
        run: |
          cd youtube_base && \
          poetry run python manage.py migrate && \
          poetry run python manage.py loaddata youtubers/fixtures/categories.json && \
          poetry run python manage.py loaddata youtubers/fixtures/youtubers.json && \
          poetry run echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'admin')"
      - name: Run pytest
        run: |
          poetry run pytest -v
          if [ $? -ne 0 ]; then
            echo "Tests failed. Aborting push."
            exit 1
          fi
      - name: Run users unit tests
        run: |
          poetry run python youtube_base/manage.py test users
      - name: Run youtubers unit tests
        run: |
          poetry run python youtube_base/manage.py test youtubers
